#include "pool_test_circuit.hpp"

void __pool__float_neg(Index* dest, Index* op1, Index* op2) {
    Index __obliv_0 = __pool__NewVar();
    Index __obliv_1 = __pool__NewVar();
    Index __obliv_2 = __pool__NewVar();
    Index __obliv_3 = __pool__NewVar();
    Index __obliv_4 = __pool__NewVar();
    Index __obliv_5 = __pool__NewVar();
    Index __obliv_6 = __pool__NewVar();
    Index __obliv_7 = __pool__NewVar();
    Index __obliv_8 = __pool__NewVar();
    Index __obliv_9 = __pool__NewVar();
    Index __obliv_10 = __pool__NewVar();
    Index __obliv_11 = __pool__NewVar();
    Index __obliv_12 = __pool__NewVar();
    Index __obliv_13 = __pool__NewVar();
    Index __obliv_14 = __pool__NewVar();
    Index __obliv_15 = __pool__NewVar();
    Index __obliv_16 = __pool__NewVar();
    Index __obliv_17 = __pool__NewVar();
    Index __obliv_18 = __pool__NewVar();
    Index __obliv_19 = __pool__NewVar();
    Index __obliv_20 = __pool__NewVar();
    Index __obliv_21 = __pool__NewVar();
    Index __obliv_22 = __pool__NewVar();
    Index __obliv_23 = __pool__NewVar();
    Index __obliv_24 = __pool__NewVar();
    Index __obliv_25 = __pool__NewVar();
    Index __obliv_26 = __pool__NewVar();
    Index __obliv_27 = __pool__NewVar();
    Index __obliv_28 = __pool__NewVar();
    Index __obliv_29 = __pool__NewVar();
    Index __obliv_30 = __pool__NewVar();
    Index __obliv_31 = __pool__NewVar();
    Index __tmp__01 = __pool__XOR(__obliv_31, *op2);
    __pool__RELEASE(__obliv_31);
    __obliv_31 = __pool__COPY(__tmp__01);
    *(dest+0) = __pool__COPY(__obliv_0);
    *(dest+1) = __pool__COPY(__obliv_1);
    *(dest+2) = __pool__COPY(__obliv_2);
    *(dest+3) = __pool__COPY(__obliv_3);
    *(dest+4) = __pool__COPY(__obliv_4);
    *(dest+5) = __pool__COPY(__obliv_5);
    *(dest+6) = __pool__COPY(__obliv_6);
    *(dest+7) = __pool__COPY(__obliv_7);
    *(dest+8) = __pool__COPY(__obliv_8);
    *(dest+9) = __pool__COPY(__obliv_9);
    *(dest+10) = __pool__COPY(__obliv_10);
    *(dest+11) = __pool__COPY(__obliv_11);
    *(dest+12) = __pool__COPY(__obliv_12);
    *(dest+13) = __pool__COPY(__obliv_13);
    *(dest+14) = __pool__COPY(__obliv_14);
    *(dest+15) = __pool__COPY(__obliv_15);
    *(dest+16) = __pool__COPY(__obliv_16);
    *(dest+17) = __pool__COPY(__obliv_17);
    *(dest+18) = __pool__COPY(__obliv_18);
    *(dest+19) = __pool__COPY(__obliv_19);
    *(dest+20) = __pool__COPY(__obliv_20);
    *(dest+21) = __pool__COPY(__obliv_21);
    *(dest+22) = __pool__COPY(__obliv_22);
    *(dest+23) = __pool__COPY(__obliv_23);
    *(dest+24) = __pool__COPY(__obliv_24);
    *(dest+25) = __pool__COPY(__obliv_25);
    *(dest+26) = __pool__COPY(__obliv_26);
    *(dest+27) = __pool__COPY(__obliv_27);
    *(dest+28) = __pool__COPY(__obliv_28);
    *(dest+29) = __pool__COPY(__obliv_29);
    *(dest+30) = __pool__COPY(__obliv_30);
    *(dest+31) = __pool__COPY(__obliv_31);
    __pool__RELEASE(__obliv_0);
	__pool__RELEASE(__obliv_1);
	__pool__RELEASE(__obliv_2);
	__pool__RELEASE(__obliv_3);
	__pool__RELEASE(__obliv_4);
	__pool__RELEASE(__obliv_5);
	__pool__RELEASE(__obliv_6);
	__pool__RELEASE(__obliv_7);
	__pool__RELEASE(__obliv_8);
	__pool__RELEASE(__obliv_9);
	__pool__RELEASE(__obliv_10);
	__pool__RELEASE(__obliv_11);
	__pool__RELEASE(__obliv_12);
	__pool__RELEASE(__obliv_13);
	__pool__RELEASE(__obliv_14);
	__pool__RELEASE(__obliv_15);
	__pool__RELEASE(__obliv_16);
	__pool__RELEASE(__obliv_17);
	__pool__RELEASE(__obliv_18);
	__pool__RELEASE(__obliv_19);
	__pool__RELEASE(__obliv_20);
	__pool__RELEASE(__obliv_21);
	__pool__RELEASE(__obliv_22);
	__pool__RELEASE(__obliv_23);
	__pool__RELEASE(__obliv_24);
	__pool__RELEASE(__obliv_25);
	__pool__RELEASE(__obliv_26);
	__pool__RELEASE(__obliv_27);
	__pool__RELEASE(__obliv_28);
	__pool__RELEASE(__obliv_29);
	__pool__RELEASE(__obliv_30);
	__pool__RELEASE(__obliv_31);
    __pool__RELEASE(__tmp__01);
}
